#env:
#  es2021: true
#extends:
#  - standard-with-typescript
#  - plugin:vue/vue3-essential
#parserOptions:
#  ecmaVersion: latest
#  sourceType: module
#plugins:
#  - vue
#rules: {}

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:vue/vue3-recommended
  - prettier
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: true
  tsconfigRootDir: __dirname
plugins:
  - '@typescript-eslint'
root: true
overrides:
  - files:
      - '*.vue'
    extends:
      - 'plugin:@typescript-eslint/disable-type-checked'
