#env:
#  es2021: true
#extends:
#  - standard-with-typescript
#  - plugin:vue/vue3-essential
#parserOptions:
#  ecmaVersion: latest
#  sourceType: module
#plugins:
#  - vue
#rules: {}

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
root: true
