env:
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
rules:
  'prettier/prettier': error
